In [1]:
import pandas as pd

In [2]:
pd.read_csv('pandastest.csv')

      name           email-id     address  pincode     surname
0      rik  rikbale@gmail.com      howrah   711101        show
1    rudra    rudra@gmail.com    ludhiana   877775  chatterjee
2  surajit   sujjit@gmail.com     kalyani   700001       nandi
3    indra    indra@gmail.com  balitikuri   711102       ghosh

In [4]:
pd.read_csv('E:\jupyter notebook files\ohana-api-master\ohana-api-master\data\sample-csv\locations.csv')

,id,organization_id,accessibility,admin_emails,alternate_name,description,email,languages,latitude,longitude,name,short_desc,transportation,website,virtual
0,1,1,"disabled_parking, ramp, restroom, wheelchair",NaN,NaN,A walk-in center for older adults that provide...,NaN,"Spanish, Tagalog",37.477227,-122.213221,Fair Oaks Adult Activity Center,A multipurpose senior citizens' center serving...,SAMTRANS stops in front.,NaN,False
1,2,1,wheelchair,NaN,NaN,Provides training and job placement to eligibl...,NaN,"Chinese (Mandarin), Tagalog, Italian, Spanish",37.563984,-122.325799,Second Career Employment Program,Provides training and job placement to eligibl...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
2,3,1,NaN,NaN,NaN,Offers supportive counseling services to San M...,NaN,"Chinese (Cantonese), Chinese (Mandarin), Tagal...",37.563984,-122.325799,Senior Peer Counseling,Offers supportive counseling services to older...,Service is provided in person's home or at a m...,NaN,False
3,4,1,wheelchair,NaN,NaN,Provides supervised visitation services and a ...,NaN,Spanish,37.563984,-122.325799,Family Visitation Center,Provides supervised visitation services and a ...,"SAMTRANS stops within 1 block, CALTRAIN stops ...",NaN,False
4,5,1,wheelchair,NaN,NaN,Provides fixed 8% short term loans to eligible...,NaN,"Hindi, Spanish",37.563984,-122.325799,Economic Self - Sufficiency Program,Makes small loans to working families.,SAMTRANS stops within 1 block. CALTRAIN stops ...,NaN,False
5,6,2,"disabled_parking, wheelchair",NaN,NaN,A multipurpose center offering a wide variety ...,NaN,"Tagalog, Spanish",37.448020,-122.180590,Little House,A multipurpose senior citizens' center.,"SAMTRANS stops within 3 blocks, RediWheels and...",NaN,False
6,7,2,"ramp, restroom, disabled_parking, wheelchair",NaN,NaN,Rosener House is a day center for older adults...,NaN,"Spanish, Tagalog, Vietnamese",37.444178,-122.183093,Rosener House Adult Day Services,A day center for adults age 50 or over.,Transportation can be arranged via Redi-Wheels...,NaN,False
7,8,2,NaN,NaN,NaN,Delivers a hot meal to the home of persons age...,NaN,Spanish,37.448020,-122.180590,Meals on Wheels - South County,Will deliver a hot meal to the home of persons...,Not necessary for service.,NaN,False
8,9,3,"ramp, restroom, wheelchair",NaN,NaN,"Provides general reading material, including b...",NaN,Spanish,37.478502,-122.214143,Fair Oaks Branch,Provides general reading materials and referen...,SAMTRANS stops in front.,NaN,False
9,10,3,"elevator, tape_braille, ramp, restroom, disabl...",NaN,NaN,"Provides general reading and media materials, ...",NaN,Spanish,37.483842,-122.227395,Main Library,Provides general reference and reading materia...,SAMTRANS stops within 1 block; CALTRAIN stops ...,NaN,False
10,11,3,ramp,NaN,NaN,"Provides general reading materials, including ...",NaN,NaN,37.466553,-122.243090,Schaberg Branch,Provides general reading materials and referen...,SAMTRANS stops within 1 block.,NaN,False
11,12,3,"disabled_parking, elevator, ramp, restroom",ohana@gmail.com,NaN,Offers an intergenerational literacy program f...,NaN,NaN,37.483842,-122.227395,Project Read,Offers an intergenerational literacy program f...,SAMTRANS stops within 1 block.,NaN,False
12,13,3,NaN,NaN,NaN,"Provides general reading materials, including ...",NaN,NaN,37.530423,-122.258643,Redwood Shores Branch,Provides general reading materials and referen...,NaN,NaN,False
13,14,4,wheelchair,NaN,NaN,"Provides food, clothing, bus tokens and shelte...",NaN,Spanish,37.491386,-122.231568,Redwood City Corps,Provides a variety of emergency services to lo...,SAMTRANS stops nearby.,NaN,False
14,15,4,wheelchair,NaN,NaN,Provides a long-term (6-12 month) residential ...,NaN,Spanish,37.748899,-122.420367,Adult Rehabilitation Center,Long-term (6-12 month) residential treatment p...,"MUNI - 26 Valencia, Mission Street lines.",NaN,False
15,16,4,NaN,NaN,NaN,Provides emergency assistance including food a...,NaN,Korean,37.356900,-122.060002,Sunnyvale Corps,Provides emergency assistance to persons in im...,VTA stops within 4 blocks.,NaN,False
16,17,4,wheelchair,NaN,NaN,"Provides emergency food, clothing and furnitur...",NaN,NaN,37.644590,-122.422490,South San Francisco Citadel Corps,Provides emergency food and clothing and furni...,"SAMTRANS stops within 1 block, BART stops with...",NaN,False
17,18,5,"cd, restroom, wheelchair",NaN,NaN,Provides free medical care to those in need. O...,NaN,Spanish,37.468614,-122.206798,Redwood City Free Medical Clinic,Provides free medical care to those in need.,SAMTRANS stops within 2 blocks.,http://www.samaritanhouse.com,False
18,19,5,"elevator, ramp, wheelchair",NaN,NaN,Provides free medical and dental care to those...,NaN,Spanish,37.532694,-122.293124,San Mateo Free Medical Clinic,Provides free medical and dental care to those...,SAMTRANS stops within 1 block.,http://www.samaritanhouse.com,False
19,20,6,NaN,NaN,NaN,no phone,NaN,NaN,NaN,NaN,Location with no phone,no phone,NaN,NaN,True
20,21,7,"elevator, restroom",NaN,NaN,This is a description,NaN,NaN,37.529194,-122.287161,Admin Test Location,This is a short description,SAMTRANS stops within 1/2 mile.,NaN,False
21,22,8,"disabled_parking, restroom, wheelchair",foo@bar.com,The Test Spot,[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,info@example.org,"Cantonese, Russian, Spanish, Tagalog, Taiwanese",37.772640,-122.409915,Example Location,[NOTE THIS IS NOT A REAL ENTRY--THIS IS FOR TE...,SAMTRANS stops within 1 block,http://www.example.org,False

In [5]:
pd.read_csv('E:\jupyter notebook files\ohana-api-master\ohana-api-master\data\sample-csv\services.csv')

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

Pandas considers the first row as header/column header.

And the indexes are generated by the pandas.

Pandas only works with structured data.

In [8]:
df = pd.read_csv('taxonomy.csv')

#### The entire table generated by Pandas is called as Dataframe.

In [9]:
df

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3     101-02-01             Help Pay for Food    101-02        Emergency Cash
4     101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285   111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [11]:
type(df) #DataFrame Datatype

pandas.core.frame.DataFrame

### In pandas, we will see two types of Datatypes:
- DataFrame
- Series

### So, by default pandas considers the first row of the file as column names.

### If any dataset doesnot have column names, then pandas will set the first row/record as the column name.

In [12]:
# for example

pd.read_csv('taxonomy.csv')

           101                     Emergency Unnamed: 2            Unnamed: 3
0       101-01             Disaster Response        101             Emergency
1       101-02                Emergency Cash        101             Emergency
2    101-02-01             Help Pay for Food     101-02        Emergency Cash
3    101-02-02       Help Pay for Healthcare     101-02        Emergency Cash
4    101-02-03          Help Pay for Housing     101-02        Emergency Cash
..         ...                           ...        ...                   ...
284  111-01-07              Workplace Rights     111-01  Advocacy & Legal Aid
285     111-02                     Mediation        111                 Legal
286     111-03                        Notary        111                 Legal
287     111-04                Representation        111                 Legal
288     111-05  Translation & Interpretation        111                 Legal

[289 rows x 4 columns]

But we can add our own column names if we want.

pd.read_csv() takes many arguments. Two of them are called header and names. If we set header = None, then it won't take the very first row as column name.

In [13]:
pd.read_csv('taxonomy.csv', header=None)

             0                             1       2                     3
0          101                     Emergency     NaN                   NaN
1       101-01             Disaster Response     101             Emergency
2       101-02                Emergency Cash     101             Emergency
3    101-02-01             Help Pay for Food  101-02        Emergency Cash
4    101-02-02       Help Pay for Healthcare  101-02        Emergency Cash
..         ...                           ...     ...                   ...
285  111-01-07              Workplace Rights  111-01  Advocacy & Legal Aid
286     111-02                     Mediation     111                 Legal
287     111-03                        Notary     111                 Legal
288     111-04                Representation     111                 Legal
289     111-05  Translation & Interpretation     111                 Legal

[290 rows x 4 columns]

If we want to add own custom column name, then we have to pass these names inside a list as names arguments/

In [14]:
pd.read_csv('taxonomy.csv', names=['col1','col2', 'col3','col4'])

          col1                          col2    col3                  col4
0          101                     Emergency     NaN                   NaN
1       101-01             Disaster Response     101             Emergency
2       101-02                Emergency Cash     101             Emergency
3    101-02-01             Help Pay for Food  101-02        Emergency Cash
4    101-02-02       Help Pay for Healthcare  101-02        Emergency Cash
..         ...                           ...     ...                   ...
285  111-01-07              Workplace Rights  111-01  Advocacy & Legal Aid
286     111-02                     Mediation     111                 Legal
287     111-03                        Notary     111                 Legal
288     111-04                Representation     111                 Legal
289     111-05  Translation & Interpretation     111                 Legal

[290 rows x 4 columns]

In the above example, there are 4 columns. What if we add 5 column names

In [15]:
pd.read_csv('taxonomy.csv', names=['col1','col2', 'col3','col4','col5'])

,col1,col2,col3,col4,col5
0,101,Emergency,NaN,NaN,NaN
1,101-01,Disaster Response,101,Emergency,NaN
2,101-02,Emergency Cash,101,Emergency,NaN
3,101-02-01,Help Pay for Food,101-02,Emergency Cash,NaN
4,101-02-02,Help Pay for Healthcare,101-02,Emergency Cash,NaN
...,...,...,...,...,...
285,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid,NaN
286,111-02,Mediation,111,Legal,NaN
287,111-03,Notary,111,Legal,NaN
288,111-04,Representation,111,Legal,NaN
289,111-05,Translation & Interpretation,111,Legal,NaN

#### It will show another column, but NaN in the data. NaN = not a number

Let's try with  column names

In [16]:
pd.read_csv('taxonomy.csv', names=['col1','col2'])

                                          col1                  col2
101       Emergency                        NaN                   NaN
101-01    Disaster Response                101             Emergency
101-02    Emergency Cash                   101             Emergency
101-02-01 Help Pay for Food             101-02        Emergency Cash
101-02-02 Help Pay for Healthcare       101-02        Emergency Cash
...                                        ...                   ...
111-01-07 Workplace Rights              111-01  Advocacy & Legal Aid
111-02    Mediation                        111                 Legal
111-03    Notary                           111                 Legal
111-04    Representation                   111                 Legal
111-05    Translation & Interpretation     111                 Legal

[290 rows x 2 columns]

It takes the first two columns as indexes.

IF the dataset/CSV file don't have commas (,) as delimitter, then we have to manually set the delimitter

In [ ]:
pd.read_csv('pandastest.csv', sep= '@') # sep = 'the delimiter sign'

We won't be able to use more than one separators at a time.

## Skip row numbers

In [4]:
pd.read_csv('pandastest.csv')

      name           email-id     address  pincode     surname
0      rik  rikbale@gmail.com      howrah   711101        show
1    rudra    rudra@gmail.com    ludhiana   877775  chatterjee
2  surajit   sujjit@gmail.com     kalyani   700001       nandi
3    indra    indra@gmail.com  balitikuri   711102       ghosh

In [3]:
pd.read_csv('pandastest.csv', skiprows= [1,3])

    name         email-id     address  pincode     surname
0  rudra  rudra@gmail.com    ludhiana   877775  chatterjee
1  indra  indra@gmail.com  balitikuri   711102       ghosh

------

In [6]:
df = pd.read_csv('services.csv')

In [8]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [7]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

object is nothing but strings. In Pandas, object is string.

In [10]:
#sample records

df.head() #By default it shows first 5 records

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [11]:
df.tail() #it shows last 5 records

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [12]:
df.head(2) #first two records

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [13]:
df.tail(2) #last two records

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [15]:
df.columns #list of all column names

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [17]:
#show specific columns

df['email'] # column name

0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21    passports@example.org
22                      NaN
Name: email, dtype: object

In [19]:
a = df['name']

In [20]:
type(a)

pandas.core.series.Series

In [21]:
df['name','location_id']

KeyError: ('name', 'location_id')

In [22]:
df[['name','location_id']]

                                    name  location_id
0        Fair Oaks Adult Activity Center            1
1       Second Career Employment Program            2
2                 Senior Peer Counseling            3
3               Family Visitation Center            4
4      Economic Self-Sufficiency Program            5
5   Little House Recreational Activities            6
6       Rosener House Adult Day Services            7
7         Meals on Wheels - South County            8
8                       Fair Oaks Branch            9
9                           Main Library           10
10                       Schaberg Branch           11
11                          Project Read           12
12                 Redwood Shores Branch           13
13                    Redwood City Corps           14
14           Adult Rehabilitation Center           15
15                       Sunnyvale Corps           16
16     South San Francisco Citadel Corps           17
17                         Project Smile           18
18         San Mateo Free Medical Clinic           19
19             Service with blank fields           20
20       Service for Admin Test Location           21
21                       Passport Photos           22
22                  Example Service Name           22

In [23]:
b = df[['name','location_id']]

In [24]:
type(b)

pandas.core.frame.DataFrame

In [25]:
df[['name']]

                                    name
0        Fair Oaks Adult Activity Center
1       Second Career Employment Program
2                 Senior Peer Counseling
3               Family Visitation Center
4      Economic Self-Sufficiency Program
5   Little House Recreational Activities
6       Rosener House Adult Day Services
7         Meals on Wheels - South County
8                       Fair Oaks Branch
9                           Main Library
10                       Schaberg Branch
11                          Project Read
12                 Redwood Shores Branch
13                    Redwood City Corps
14           Adult Rehabilitation Center
15                       Sunnyvale Corps
16     South San Francisco Citadel Corps
17                         Project Smile
18         San Mateo Free Medical Clinic
19             Service with blank fields
20       Service for Admin Test Location
21                       Passport Photos
22                  Example Service Name

In [26]:
type(df[['name']])

pandas.core.frame.DataFrame

In [27]:
ls

 Volume in drive C is Windows
 Volume Serial Number is D0C1-5A67

 Directory of C:\Users\rouna

21-12-2022  17:50    <DIR>          .
22-10-2022  16:10    <DIR>          ..
21-12-2022  17:50    <DIR>          .conda
21-10-2022  16:03                25 .condarc
05-11-2022  15:57    <DIR>          .continuum
20-12-2022  20:12    <DIR>          .ipynb_checkpoints
19-10-2022  19:43    <DIR>          .ipython
20-11-2022  17:05    <DIR>          .jupyter
13-11-2022  01:31    <DIR>          .matplotlib
12-11-2022  00:02    <DIR>          .ms-ad
18-11-2022  19:24    <DIR>          __pycache__
12-11-2022  17:37            33,491 12th November iNeuron.ipynb
13-11-2022  17:26            25,890 13th November iNeuron.ipynb
11-12-2022  16:22    <DIR>          19.3 MongoDB
21-11-2022  18:25            55,345 19th November iNeuron (Imran).ipynb
01-11-2022  18:41            22,102 1st Oct ineuron(operators, if-else).ipynb
26-11-2022  18:11            22,149 20th November iNeuron (Imran).ipynb
01-11-2022  18:38            10,583 24th Sept ineuron (Variables, Data types).ipynb
01-11-2022  18:40            34,485 25th Sept ineuron (User input, Type-casting).ipynb
29-10-2022  17:42           215,733 29th October iNeuron.ipynb
03-12-2022  15:13               714 3rd December - iNeuron.ipynb
13-11-2022  12:03           224,326 6.3 python list ineuron.ipynb
21-10-2022  16:27           197,746 6.4 python tuple and sets.ipynb
29-10-2022  14:53           199,514 6.5 Dictionary.ipynb
01-11-2022  18:43           117,731 8th Oct(String Methods).ipynb
28-05-2022  00:23             1,173 addresses.csv
21-10-2022  16:03    <DIR>          anaconda3
21-10-2022  16:27            10,768 Array.ipynb
21-10-2022  16:27            12,652 Assignments_001_25th_Sept.ipynb
04-12-2022  15:38            51,867 car.data
12-12-2022  16:56           628,633 carbon_nanotubes.csv
20-12-2022  20:07             3,016 Cassandra.ipynb
17-12-2022  17:19               162 check443.txt
13-11-2022  01:16            34,154 ckd-dataset-v2.csv
21-12-2022  12:56    <DIR>          Contacts
28-05-2022  00:23             1,589 contacts.csv
13-11-2022  01:41         1,697,172 coviddatasets.csv
19-12-2022  19:34                36 demo.json
05-08-2020  21:27            23,873 diabetes.csv
12-12-2022  16:04            63,809 diabetes_json.json
21-10-2022  16:27            12,661 Dictionaries & Sets.ipynb
19-10-2022  01:09    <DIR>          Documents
21-12-2022  17:50    <DIR>          Downloads
03-12-2022  15:44            34,624 Exception Handling.ipynb
19-10-2022  01:07    <DIR>          Favorites
20-12-2022  20:09            81,388 File System.ipynb
17-12-2022  17:34            26,335 FSDS 2.0 Assignment 11th Dec.ipynb
30-10-2022  13:28             4,375 FSDS bootcamp assignment 29th Oct.ipynb
21-10-2022  16:27            12,833 FSDS_bootcamp_assignment_002_Oct_01.ipynb
21-10-2022  16:27             6,765 FSDS_bootcamp_assignment_003_Oct_08.ipynb
21-10-2022  16:27             4,177 FSDS_bootcamp_assignment_004_Oct_09.ipynb
01-11-2022  18:51             6,660 FSDS_bootcamp_assignment_005_Oct_16.ipynb
12-11-2022  13:09            29,641 FSDS_bootcamp_assignment_29th Oct.ipynb
26-10-2022  14:16            30,112 Function and holiday task.ipynb
01-12-2022  18:41                 0 glass.csv
01-12-2022  18:43            11,903 glass.data
19-12-2022  18:55                57 google.txt
28-05-2022  00:23               277 holiday_schedules.csv
13-11-2022  16:58           277,421 imagaae.png
19-12-2022  19:11           277,421 imagaae_copy.png
13-12-2022  21:55             8,192 ineuron.db
01-12-2022  21:53            51,092 Iterator & Generator.ipynb
14-12-2022  15:33            12,288 jobdb.db
14-12-2022  15:43             8,720 jobdb.db-journal
19-10-2022  01:07    <DIR>          Links
28-05-2022  00:23            18,015 locations.csv
10-11-2022  19:52             5,663 Logging.ipynb
26-05-2022  15:45           161,651 LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx
26-05-2022  15:45           161,410 LUSID Excel - Maintain a product in multiple currencies and share classes.xlsx
26-05-2022  15:45            95,503 LUSID Excel - Manage instruments with economic definitions.xlsx
26-05-2022  15:45            84,319 LUSID Excel - Manage Orders.xlsx
26-05-2022  15:45           137,753 LUSID Excel - Manage your investment strategies.xlsx
26-05-2022  15:45           184,013 LUSID Excel - Setting up your IBOR.xlsx
26-05-2022  15:45           136,632 LUSID Excel - Setting up your market data.xlsx
28-05-2022  00:23             1,610 mail_addresses.csv
21-10-2022  16:27            15,396 Misc_exercise.ipynb
14-11-2022  19:33             9,280 Modules and packages.ipynb
13-12-2022  23:13         2,062,668 MongoDB - Part1- Sudhansu Sir.ipynb
19-10-2022  01:07    <DIR>          Music
18-11-2022  19:23               803 mydictionary.py
03-12-2022  18:09           154,371 MySQL+Python Part_1 - Sudhanshu Sir.ipynb
17-12-2022  14:45        10,712,596 MySQL+Python Part_2 - Sudhanshu Sir.ipynb
20-12-2022  12:40            25,327 Namespaces & Decorators.ipynb
21-10-2022  16:27            17,593 Numpy Arrays.ipynb
21-12-2022  17:11    <DIR>          OneDrive
29-11-2022  21:51            58,598 OOPS Class - Sudhanshu Sir.ipynb
30-11-2022  17:32            65,450 OOPS part 2 - Sudhanshu Sir.ipynb
30-11-2022  17:32            30,385 OOPS part 3 - Sudhanshu Sir.ipynb
28-05-2022  00:23             2,281 organizations.csv
21-12-2022  17:50           217,098 Pandas - Sudhanshu Sir.ipynb
20-12-2022  20:36               228 pandastest.csv
20-12-2022  20:34             9,694 pandastest.xlsx
13-12-2022  21:53             8,192 person.db
19-12-2022  20:21                63 person.pkl
28-05-2022  00:23             2,092 phones.csv
28-05-2022  00:23                60 programs.csv
21-10-2022  16:27             7,001 Python Basic Assignment 1.ipynb
17-11-2022  21:09             5,429 Python Basic Assignment 15.ipynb
16-11-2022  13:43            11,630 Python Basic Assignment 16.ipynb
15-11-2022  13:10            10,180 Python Basic Assignment 17.ipynb
10-12-2022  21:00            14,302 Python Basic Assignment 19.ipynb
21-10-2022  16:27            12,589 Python Basic Assignment 2.ipynb
09-11-2022  17:47             7,012 Python Basic Assignment 3.ipynb
21-10-2022  16:27            15,653 Python Basic Assignment 4.ipynb
05-11-2022  14:54            10,460 Python Basic assignment 5.ipynb
07-11-2022  17:17            20,909 Python Basic Assignment 6.ipynb
01-11-2022  18:24            30,661 Python Function - part 2- Sudhanshu Sir.ipynb
01-11-2022  18:24            16,705 Python Function - Sudhanshu Sir.ipynb
22-10-2022  21:59            10,166 Python Program Discussion in Loops.ipynb
28-05-2022  00:23               350 regular_schedules.csv
20-12-2022  20:05               300 rik-token.json
19-10-2022  01:07    <DIR>          Saved Games
19-10-2022  01:21    <DIR>          Searches
28-05-2022  00:23            19,128 services.csv
04-12-2022  15:39           358,224 sql day 2 .ipynb
17-12-2022  15:04            71,260 SQLite.ipynb
20-12-2022  21:11            14,578 taxonomy.csv
21-11-2022  12:54               466 test.log
19-12-2022  19:05            11,000 test.text
19-12-2022  18:59                33 test.txt
05-11-2022  15:37               133 test1.txt
10-11-2022  19:37             1,374 test2.log
10-11-2022  19:47             1,508 test3.log
05-11-2022  16:16                 0 test3.txt
05-11-2022  16:19             1,327 test5.txt
11-11-2022  13:11               185 testmodule.py
11-11-2022  13:09               185 testmodule.py.bak
30-10-2022  16:31            16,812 tnt flash tv.docx
21-10-2022  16:27             2,096 Tuples.ipynb
13-11-2022  12:26             2,935 Untitled.ipynb
13-11-2022  01:43            85,380 Untitled1.ipynb
18-11-2022  19:35             2,059 Untitled2.ipynb
19-10-2022  23:33    <DIR>          Videos
16-12-2022  12:00           236,180 vocabenron.txt
16-12-2022  12:00            55,467 vocabkos.txt
16-12-2022  12:00           100,807 vocabnips.txt
16-12-2022  12:00         1,345,665 vocabnytimes.txt
16-12-2022  12:00         1,460,248 vocabpubmed.txt
             116 File(s)     22,924,821 bytes
              22 Dir(s)  90,529,427,456 bytes free

In [28]:
pd.read_excel('LUSID Excel - Manage Orders.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [29]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     -------------------------------------- 242.1/242.1 kB 3.0 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10
Note: you may need to restart the kernel to use updated packages.

In [3]:
pd.read_excel('LUSID Excel - Manage Orders.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,This sheet allows you to manage executions:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. List executions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. Get execution,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. Upsert executions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,MyExecutionCode01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

By default, it will show the first sheet of the excel file.

To show other sheets, we have to write sheet names.

#### How to read other sheets from an excel file

In [4]:
pd.read_excel('LUSID Excel - Manage Orders.xlsx', sheet_name= 'Allocations')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,This sheet allows you to manage Allocations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetAllocation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,MyAllocation001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,MyAllocation002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df =pd.read_excel('LUSID Excel - Manage Orders.xlsx')

How to get all sheetnames in a excel file

In [7]:
df1 = pd.ExcelFile('LUSID Excel - Manage Orders.xlsx')

In [8]:
df1.sheet_names

['Executions', 'Orders', 'Allocations', 'Placements', 'Blocks']

In [9]:
for i in df1.sheet_names:
    pd.read_excel('LUSID Excel - Manage Orders.xlsx', sheet_name=i)

------------------

Read csv file directly from the gitbhub raw link

In [11]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>